### PR TITLE
volume-widget: added arguments, fixed colors for light themes

### LINKED ISSUE #396: volume-widget: Mixer selection
I would like to suggest changing the string _'Master'_ at line **20-23** in `volume-widget/volume.lua` to an user passed argument - let's call it `mixctrl` - that falls back to _'Master'_ since the mixer control isn't necessarily called that way. So, mostly users won't need to pass any argument to `mixctrl`, however users with more sound devices relaying on alsa could specify their correct mixer control. These are all modifications I needed to do in `volume-widget/volume.lua` so the widget could work for me, since I'm using only alsa on my system and I use a external USB audio interface to handle audio from my computer:

```diff
20,23c20,27
< local function GET_VOLUME_CMD(device) return 'amixer -D ' .. device .. ' sget Master' end
< local function INC_VOLUME_CMD(device, step) return 'amixer -D ' .. device .. ' sset Master ' .. step .. '%+' end
< local function DEC_VOLUME_CMD(device, step) return 'amixer -D ' .. device .. ' sset Master ' .. step .. '%-' end
< local function TOG_VOLUME_CMD(device) return 'amixer -D ' .. device .. ' sset Master toggle' end
---
> local function GET_VOLUME_CMD(device, mixctrl)
> 	return "amixer -D " .. device .. " sget '" .. mixctrl .. "'" end
> local function INC_VOLUME_CMD(device, mixctrl, step)
> 	return 'amixer -D '..device..' sset "'..mixctrl..'" '..step..'%+' end
> local function DEC_VOLUME_CMD(device, mixctrl, step)
> 	return 'amixer -D '..device..' sset "'..mixctrl..'" '..step.. '%-' end
> local function TOG_VOLUME_CMD(device, mixctrl)
> 	return 'amixer -D '..device..' sset "'..mixctrl..'" toggle' end
170a175
> 	local mixctrl = args.mixctrl or 'Master'
189c194
<         spawn.easy_async(INC_VOLUME_CMD(device, s or step), function(stdout) update_graphic(volume.widget, stdout) end)
---
>         spawn.easy_async(INC_VOLUME_CMD(device, mixctrl, s), function(stdout) update_graphic(volume.widget, stdout) end)
193c198
<         spawn.easy_async(DEC_VOLUME_CMD(device, s or step), function(stdout) update_graphic(volume.widget, stdout) end)
---
>         spawn.easy_async(DEC_VOLUME_CMD(device, mixctrl, s), function(stdout) update_graphic(volume.widget, stdout) end)
197c202
<         spawn.easy_async(TOG_VOLUME_CMD(device), function(stdout) update_graphic(volume.widget, stdout) end)
---
>         spawn.easy_async(TOG_VOLUME_CMD(device, mixctrl), function(stdout) update_graphic(volume.widget, stdout) end)
216,217c221,222
<                     awful.button({}, 4, function() volume:inc() end),
<                     awful.button({}, 5, function() volume:dec() end),
---
>                     awful.button({}, 4, function() volume:inc(step) end),
>                     awful.button({}, 5, function() volume:dec(step) end),
223c228
<     watch(GET_VOLUME_CMD(device), refresh_rate, update_graphic, volume.widget)
---
>     watch(GET_VOLUME_CMD(device, mixctrl), refresh_rate, update_graphic, volume.widget)
229d233
< 
```
And inside `rc.lua` everything go as always, just the user has a one more argument to modify, if needed:

```lua
. . .

local volume_widget = require("awesome-wm-widgets.volume-widget.volume")

. . .

            volume_widget{
                 widget_type = 'arc',
                 device = 'default',
                 mixctrl = 'UMC404HD 192k Output',                                                                                                                                        
                 size = 16,
                 step = 1
            },
. . .
```

### PR DESCRIPTION
**Pull request by Luka5W**
#### added options
- card: `amixer -c [card]`
  - multiple cards support
- value_type: `amixer -M` or `-R`
  - from the command help:
    ```
    -R,--raw-volume Use the raw value (default)
    -M,--mapped-volume Use the mapped volume
    ```
    no idea how this actually works, but lowering the volume using `-R` takes big steps at first and then they become smaller.
    when using `-M` the steps stay constant (5% relative to 100%/ 0dB) 
- mixctrl: (`amixer [args] [command] [mixctrl] [command ct'd]`)
  - multiple mixers support
  - fixes #396 (used the same key for compatibility with the awesome rc.lua of those users who applied the code suggested in the issue) 
- toggle_cmd: overrides `amixer ...` command for (un)muting
  - allows users to replace the broken `amixer sset [mixer] toggle` command which uses `amixer sset [mixer] [un]mute` with anything like `pactl set-sink-mute 0 toggle` which worked for me

#### fixed colors for light themes

only for volume, i might create additional PRs for other widgets i use (see ).

tested with themes:
- gtk (with little patches to be a complete light theme)
- default

#### fixed get volume cmd

see [#df4dd6d](https://github.com/streetturtle/awesome-wm-widgets/pull/416/commits/df4dd6d0f6f51f89e43631ff35e5204534fe931a)
-M was forgotten so amixer used -R as fallback

#### todo

please let me know if the changes are ok, i will then update the readme before merging.

### CODE REVIEW

**Review by streetturtle — COMMENTED** [review]
Hey! Thanks for the PR! 👍
Looks good - I'll be able to test it later this weekend. Meanwhile, could you please update the readme.

File: volume-widget/volume.lua [hunk 1]
```diff
@@ -186,15 +203,19 @@ local function worker(user_args)
...
     end
 
     function volume:dec(s)
-        spawn.easy_async(DEC_VOLUME_CMD(device, s or step), function(stdout) update_graphic(volume.widget, stdout) end)
+        spawn.easy_async(DEC_VOLUME_CMD(card, device, mixctrl, value_type, s or step), function(stdout) update_graphic(volume.widget, stdout) end)
     end
 
     function volume:toggle()
-        spawn.easy_async(TOG_VOLUME_CMD(device), function(stdout) update_graphic(volume.widget, stdout) end)
+        if toggle_cmd == nil then
```
Comment (Luka5W) [inline volume-widget/volume.lua:214]: documentation done. i hope its understandable.

this looks a bit dirty to me. (spawn.easy_async takes some time i believe). the advantage of the current code is that the user doesn't need to take care, that the command doesn't output anything.

this is another approach:

```lua
spawn.easy_async(
    toggle_cmd == nil and TOG_VOLUME_CMD(card, device, mixctrl)
    or string.format([[sh -c "%s ; %s"]], toggle_cmd, GET_VOLUME_CMD(card, device, mixctrl)),
    function(stdout) update_graphic(volume.widget, stdout) end)
```

**Review by streetturtle — APPROVED** [review]

**Comment by streetturtle** [comment]
Thank you!
